import { describe, expect, it } from "bun:test"
import { resolveTokenBudgetConfig } from "../../src/config/token-budget-config"
import { TokenBudgetController } from "../../src/services/token-budget-controller"
import { InMemoryTokenUsageStore } from "../../src/services/token-usage-store"
import { AdaptiveExecutionControl, detectStall } from "../../src/services/adaptive-execution-control"
describe("adaptive execution control", () => {
  it("detects multi-signal stalls but does not classify one long operation alone", () => { expect(detectStall({ repeatedFailure: 0, repeatedTool: 0, unchangedDiff: 5, repeatedContext: 0, evidenceDelta: 0, tokensSinceProgress: 5000 }).stalled).toBe(false); expect(detectStall({ repeatedFailure: 3, repeatedTool: 0, unchangedDiff: 0, repeatedContext: 0, evidenceDelta: 0, tokensSinceProgress: 700 }).stalled).toBe(true) })
  it("reclaims actual unused reservation exactly once and redistributes through the existing controller", async () => { const store = new InMemoryTokenUsageStore(); const ctrl = new TokenBudgetController(resolveTokenBudgetConfig({ enabled: true, runTotal: 1000, childTotal: 500 }), { runId: "run", store }); ctrl.registerSession("s", "agent"); const reserved = await ctrl.reserveRequest({ runId: "run", sessionId: "s", agentId: "agent", requestId: "request", estimatedInputTokens: 100, maxOutputTokens: 200 }); const control = new AdaptiveExecutionControl(ctrl, store); const first = await control.reconcileCompletion({ runId: "run", reservationId: reserved.reservationId, workstreamId: "w", sessionId: "s", agentId: "agent", requestId: "request", messageId: "message", usage: { input: 50, output: 50 }, reason: "completed" }); expect(first.reclaimed).toBe(200); const duplicate = await control.reconcileCompletion({ runId: "run", reservationId: reserved.reservationId, workstreamId: "w", sessionId: "s", agentId: "agent", requestId: "request", messageId: "message", usage: { input: 50, output: 50 }, reason: "duplicate" }); expect(duplicate.reclaimed).toBe(0); expect(ctrl.getSnapshot().run.releasedUnused).toBe(200); expect(store.rebuild("run").releasedUnused).toBe(200); const result = await control.redistribute("run", "w2", "s", "agent", 100, "critical_path", "r"); expect(result.allowed).toBe(true); expect(store.read("run").some(e => e.kind === "adaptive_redistribution")).toBe(true) })
  it("opens a workstream budget handle without creating a second controller", async () => { const store = new InMemoryTokenUsageStore(); const ctrl = new TokenBudgetController(resolveTokenBudgetConfig({ enabled: true, runTotal: 1000, childTotal: 500, maxRequestOutputTokens: 500 }), { runId: "run", store }); const control = new AdaptiveExecutionControl(ctrl, store); const handle = control.openWorkstream("w", "s", "agent", "small"); expect(handle.profile).toBe("small"); const reservation = await handle.reserve({ requestId: "work-request", estimatedInputTokens: 10, maxOutputTokens: 100 }); expect(reservation.allowed).toBe(true); expect(ctrl.getSnapshot().agents).toHaveLength(1); await handle.reconcile({ reservationId: reservation.reservationId, requestId: "work-request", messageId: "work-message", usage: { input: 10, output: 10 }, reason: "completed" }); expect(ctrl.getSnapshot().run.consumed).toBe(20) })
  it("terminates a stalled workstream without leaking its reservation", async () => { const store = new InMemoryTokenUsageStore(); const ctrl = new TokenBudgetController(resolveTokenBudgetConfig({ enabled: true, runTotal: 1000, childTotal: 500 }), { runId: "run", store }); const control = new AdaptiveExecutionControl(ctrl, store); const handle = control.openWorkstream("w", "s", "agent", "normal"); const reservation = await handle.reserve({ requestId: "terminate-request", estimatedInputTokens: 10, maxOutputTokens: 100 }); expect(reservation.allowed).toBe(true); await handle.terminate("no_progress"); expect(ctrl.getSnapshot().run.reserved).toBe(0); expect(store.read("run").some(e => e.kind === "workstream_termination" && e.reason === "no_progress")).toBe(true) })
  it("terminates only after a deterministic multi-signal stall observation", async () => { const store = new InMemoryTokenUsageStore(); const ctrl = new TokenBudgetController(resolveTokenBudgetConfig({ enabled: true, runTotal: 1000, childTotal: 500 }), { runId: "run", store }); const control = new AdaptiveExecutionControl(ctrl, store); const handle = control.openWorkstream("w", "s", "agent", "normal"); const reservation = await handle.reserve({ requestId: "stall-request", estimatedInputTokens: 10, maxOutputTokens: 100 }); expect(reservation.allowed).toBe(true); const result = await handle.observe({ repeatedFailure: 3, repeatedTool: 0, unchangedDiff: 0, repeatedContext: 0, evidenceDelta: 0, tokensSinceProgress: 700 }); expect(result.stalled).toBe(true); expect(ctrl.getSnapshot().run.reserved).toBe(0); expect(store.read("run").some(e => e.kind === "workstream_termination" && e.reason === "no_progress")).toBe(true) })
})
