import type { Database } from "bun:sqlite"
import { randomUUID } from "node:crypto"

const now = () => new Date().toISOString()
export class HeidiDelegationRuntime {
  constructor(private readonly db: Database) {}
  queued(input: { childId: string; parentSessionId?: string; parentTaskRunId?: string; specialist: string; goal?: string }): void { const timestamp = now(); this.db.query("INSERT OR IGNORE INTO heidi_delegation_activity (child_id,parent_session_id,parent_task_run_id,specialist,goal,state,created_at,last_activity_at) VALUES (?,?,?,?,?,?,?,?)").run(input.childId,input.parentSessionId ?? null,input.parentTaskRunId ?? null,input.specialist,input.goal ?? null,"queued",timestamp,timestamp) }
  transition(childId: string, state: "running" | "completed" | "failed" | "cancelled" | "timed_out" | "unknown", detail?: { summary?: string; error?: string; phase?: string; currentTool?: string; toolCalls?: number }): void { const terminal = ["completed","failed","cancelled","timed_out","unknown"].includes(state); this.db.query(`UPDATE heidi_delegation_activity SET state=?, last_activity_at=?, started_at=CASE WHEN ?='running' AND started_at IS NULL THEN ? ELSE started_at END, finished_at=CASE WHEN ?=1 THEN ? ELSE finished_at END, summary=COALESCE(?,summary), error=COALESCE(?,error), phase=COALESCE(?,phase), current_tool=COALESCE(?,current_tool), tool_calls=COALESCE(?,tool_calls) WHERE child_id=?`).run(state,now(),state,now(),terminal ? 1 : 0,now(),detail?.summary ?? null,detail?.error ?? null,detail?.phase ?? null,detail?.currentTool ?? null,detail?.toolCalls ?? null,childId) }
  list(parentSessionId?: string): unknown[] { return (parentSessionId ? this.db.query("SELECT * FROM heidi_delegation_activity WHERE parent_session_id=? ORDER BY created_at DESC").all(parentSessionId) : this.db.query("SELECT * FROM heidi_delegation_activity ORDER BY created_at DESC").all()) as unknown[] }
  inspect(childId: string, ownerSessionId?: string): unknown { return this.db.query("SELECT * FROM heidi_delegation_activity WHERE child_id=? AND (parent_session_id=? OR ? IS NULL)").get(childId,ownerSessionId ?? null,ownerSessionId ?? null) }
  control(childId: string, kind: "cancel" | "steer", instruction: string | undefined, ownerSessionId: string): { status: string } { const child = this.inspect(childId, ownerSessionId) as { state?: string } | null; if (!child) return { status: "not_found_or_not_owned" }; if (["completed","failed","cancelled","timed_out","unknown"].includes(String(child.state))) return { status: "terminal" }; const id = randomUUID(); const status = kind === "cancel" ? "queued" : "unsupported"; this.db.query("INSERT INTO heidi_delegation_controls (id,child_id,kind,instruction,status,created_at) VALUES (?,?,?,?,?,?)").run(id,childId,kind,instruction ?? null,status,now()); if (kind === "cancel") this.db.query("UPDATE heidi_delegation_activity SET cancel_requested=1 WHERE child_id=?").run(childId); return { status } }
}
