/**
 * Runtime Agent Policy
 *
 * Enforces that top-level user messages use the expected primary agent.
 * Prevents silent agent substitution (e.g., "build" overriding default_agent: "heidi").
 *
 * Configuration (via flowdeck.json or opencode.json):
 *   runtimeAgent:
 *     enforcement: "strict" | "warn" | "off"
 *     expectedAgent: string (optional, defaults to effective default_agent)
 *
 * Hook: chat.message
 *   - Reads the resolved agent from output.message.agent
 *   - Compares to the effective expected primary agent
 *   - Applies enforcement only to top-level user messages
 *   - Excludes subagent sessions and synthetic/internal messages
 *
 * Identity anti-fabrication:
 *   - Appends an authoritative identity statement to output.message.system
 *   - Does not replace existing system content
 */

import { appendAuditEvent } from "./audit-log"
import type { FlowDeckConfig } from "../config/schema"

export type RuntimeAgentMode = "strict" | "warn" | "off"

export interface RuntimeAgentConfig {
  enforcement: RuntimeAgentMode
  expectedAgent?: string
}

const DEFAULT_EXPECTED_AGENT = "heidi"
const DEFAULT_MODE: RuntimeAgentMode = "strict"

/**
 * Synthetic and internal message variants that must never be enforcement targets.
 * Title, summary, compaction, and continuation are generated by OpenCode itself.
 */
const SYNTHETIC_VARIANTS = new Set([
  "title",
  "summary",
  "compaction",
  "continuation",
  "tool_call",
  "tool_result",
])

/**
 * Subagent session ID prefix pattern (child sessions).
 */
function isSubagentSession(sessionID: string): boolean {
  return sessionID ? sessionID.includes("child-") || sessionID.includes("sub-") : false
}

/**
 * Check whether a message variant is fully synthetic / internal.
 */
function isSyntheticVariant(variant?: string): boolean {
  return !!variant && SYNTHETIC_VARIANTS.has(variant)
}

/**
 * Resolve the effective runtime agent configuration.
 */
export function resolveRuntimeAgentConfig(
  flowdeckConfig: FlowDeckConfig,
  effectiveDefaultAgent?: string,
): RuntimeAgentConfig {
  const raw = (flowdeckConfig as any)?.runtimeAgent as RuntimeAgentConfig | undefined

  return {
    enforcement: raw?.enforcement ?? DEFAULT_MODE,
    expectedAgent: raw?.expectedAgent ?? effectiveDefaultAgent ?? DEFAULT_EXPECTED_AGENT,
  }
}

/**
 * Validate and enforce runtime agent identity.
 *
 * Returns a result describing the enforcement decision.
 * Does NOT throw — the caller (chat.message hook) decides whether to reject.
 */
export function enforceRuntimeAgent(input: {
  sessionID: string
  agent: string
  variant?: string
  expectedAgent: string
  enforcement: RuntimeAgentMode
  directory: string
  isSubagentSession?: boolean
  /** @deprecated not used in enforcement, available for audit */
  packageVersion?: string
}): {
  allowed: boolean
  match: boolean
  reason?: string
  auditEvent: { kind: string; detail: string }
} {
  const { sessionID, agent, variant, expectedAgent, enforcement, directory, isSubagentSession: explicitIsSubagent } = input

  // Skip subagent sessions (either via explicit metadata parentID or string fallback)
  const isSubagent = explicitIsSubagent ?? isSubagentSession(sessionID)
  if (isSubagent) {
    return {
      allowed: true,
      match: true,
      auditEvent: { kind: "session.agent_verified", detail: "subagent session skipped" },
    }
  }

  // Skip synthetic messages (title, summary, compaction, etc.)
  if (isSyntheticVariant(variant)) {
    return {
      allowed: true,
      match: true,
      auditEvent: { kind: "session.agent_verified", detail: `synthetic variant skipped: ${variant}` },
    }
  }

  // Resolve effective agent
  const resolvedAgent = agent || "unknown"
  const isMatch = resolvedAgent === expectedAgent

  if (isMatch) {
    // Match — always allow
    appendAuditEvent(directory, {
      kind: "session.agent_verified",
      session_id: sessionID,
      agent: resolvedAgent,
      decision: "allow",
      reason: `Runtime agent "${resolvedAgent}" matches expected "${expectedAgent}"`,
    })

    return {
      allowed: true,
      match: true,
      auditEvent: { kind: "session.agent_verified", detail: `match: ${resolvedAgent} == ${expectedAgent}` },
    }
  }

  // Mismatch
  const mismatchMsg = `Configured primary agent is "${expectedAgent}", but this request selected "${resolvedAgent}". Select ${expectedAgent} or change runtimeAgent.enforcement/default_agent explicitly.`
  const blockError = `FLOWDECK_AGENT_MISMATCH:\n${mismatchMsg}`

  if (enforcement === "strict") {
    appendAuditEvent(directory, {
      kind: "session.agent_mismatch",
      session_id: sessionID,
      agent: resolvedAgent,
      decision: "block",
      reason: mismatchMsg,
    })

    return {
      allowed: false,
      match: false,
      reason: blockError,
      auditEvent: { kind: "session.agent_mismatch", detail: `block: ${resolvedAgent} != ${expectedAgent}` },
    }
  }

  if (enforcement === "warn") {
    appendAuditEvent(directory, {
      kind: "session.agent_mismatch",
      session_id: sessionID,
      agent: resolvedAgent,
      decision: "warn",
      reason: mismatchMsg,
    })

    return {
      allowed: true,
      match: false,
      auditEvent: { kind: "session.agent_mismatch", detail: `warn: ${resolvedAgent} != ${expectedAgent}` },
    }
  }

  // enforcement === "off"
  return {
    allowed: true,
    match: false,
    auditEvent: { kind: "session.agent_mismatch", detail: `off: ${resolvedAgent} != ${expectedAgent} (not blocked)` },
  }
}

/**
 * Build the identity anti-fabrication system marker.
 * Prepends an authoritative identity statement without replacing existing content.
 */
export function buildIdentityMarker(agent: string, expectedAgent: string): string | null {
  if (agent === expectedAgent) {
    return `Runtime agent ID: ${agent}.\nYou must describe yourself using this runtime identity.\nDo not claim to be Heidi or the FlowDeck coordinator unless the runtime agent ID is "heidi".`
  }
  return null
}

/**
 * Apply identity marker to output.message.system.
 * Preserves existing system content — appends marker if not already present.
 */
export function applyIdentityMarker(
  systemContent: string | undefined | null,
  agent: string,
  expectedAgent: string,
): string {
  const marker = buildIdentityMarker(agent, expectedAgent)
  if (!marker) return systemContent || ""

  const existing = systemContent || ""
  if (existing.includes("Runtime agent ID:")) return existing // already applied
  return existing ? `${existing}\n\n${marker}` : marker
}
