import { describe, expect, it } from "bun:test"
import { Database } from "bun:sqlite"
import { runMigrations } from "../src/orchestration/persistence/migrations/migration-runner"
import { HeidiLearningRuntime } from "../src/services/heidi-learning-runtime"
import { configureHeidiPipelineTools, executeToolPipeline, getRegisteredPipelineExecutor, HeidiScheduler, HeidiSchedulerWorker } from "../src/services/heidi-runtime-controls"
import { HeidiDelegationRuntime } from "../src/services/heidi-delegation-runtime"

function db() { const value = new Database(":memory:"); runMigrations(value); return value }
describe("Heidi runtime closure", () => {
  it("reviews a verified completion exactly once and isolates failed review", () => { const value = db(); const runtime = new HeidiLearningRuntime(value); const first = runtime.reviewCompletion({ completionKey: "run-1", sessionId: "s", verified: true, summary: "Use bounded verification evidence before applying this reusable recovery workflow.", evidence: ["verification:passed"] }); const second = runtime.reviewCompletion({ completionKey: "run-1", sessionId: "s", verified: true, summary: "different", evidence: [] }); expect(first.status).toBe("candidate_created"); expect(second).toEqual(first); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 1 }); value.close() })
  it("dispatches registered tools through the pipeline executor", async () => { const calls: string[] = []; configureHeidiPipelineTools({ test: { execute: async (args) => { calls.push(String(args.value)); return { ok: true } } } }); const allowed = new Set(["test"]); const result = await executeToolPipeline([{ tool: "test", args: { value: "one" } }, { tool: "test", args: { value: "two" } }], allowed, getRegisteredPipelineExecutor(allowed, {}), { maxCalls: 2, timeoutMs: 1000, maxOutputBytes: 1000 }); expect(result.truncated).toBe(false); expect(calls).toEqual(["one", "two"]); await expect(executeToolPipeline([{ tool: "tool-pipeline", args: {} }], new Set(["tool-pipeline"]), async () => null, { maxCalls: 2, timeoutMs: 1000, maxOutputBytes: 1000 })).rejects.toThrow(); })
  it("supports scheduler lifecycle and restart-safe history", () => { const value = db(); const scheduler = new HeidiScheduler(value); const job = scheduler.create({ name: "nightly", prompt: "audit", scheduleType: "once", schedule: "2030-01-01T00:00:00.000Z", workspace: "/repo" }) as { id: string }; const run = scheduler.runNow(job.id) as { id: string }; scheduler.finish(run.id, "completed"); expect(scheduler.history(job.id)[0]).toMatchObject({ state: "completed" }); expect(scheduler.inspect(job.id)).toMatchObject({ enabled: 0 }); value.close() })
  it("executes a claimed scheduled job through the injected runtime and records failure safely", async () => { const value = db(); const scheduler = new HeidiScheduler(value); const job = scheduler.create({ name: "worker", prompt: "audit", scheduleType: "once", schedule: new Date(Date.now() - 1000).toISOString(), workspace: process.cwd() }) as { id: string }; let executed = false; const worker = new HeidiSchedulerWorker(scheduler, async received => { executed = received.id === job.id }); const result = await worker.runOnce(); expect(result.status).toBe("completed"); expect(executed).toBe(true); expect(scheduler.history(job.id)[0]).toMatchObject({ state: "completed" }); value.close() })
  it("projects delegated activity and refuses foreign control", () => { const value = db(); const runtime = new HeidiDelegationRuntime(value); runtime.queued({ childId: "child", parentSessionId: "parent", specialist: "tester", goal: "verify" }); expect(runtime.inspect("child", "other")).toBeNull(); expect(runtime.control("child", "cancel", undefined, "other").status).toBe("not_found_or_not_owned"); expect(runtime.control("child", "cancel", undefined, "parent").status).toBe("queued"); runtime.transition("child", "cancelled"); expect(runtime.inspect("child", "parent")).toMatchObject({ state: "cancelled" }); value.close() })
})
