import { describe, expect, it } from "bun:test"
import { mkdirSync, mkdtempSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { Database } from "bun:sqlite"
import { runMigrations } from "../src/orchestration/persistence/migrations/migration-runner"
import { HeidiLearningRuntime } from "../src/services/heidi-learning-runtime"
import { configureHeidiPipelineTools, executeToolPipeline, getRegisteredPipelineExecutor, HeidiScheduler, HeidiSchedulerWorker } from "../src/services/heidi-runtime-controls"
import { HeidiDelegationRuntime } from "../src/services/heidi-delegation-runtime"
import { heidiLearningTool } from "../src/tools/heidi-learning"

function db() { const value = new Database(":memory:"); runMigrations(value); return value }
describe("Heidi runtime closure", () => {
  it("reviews a verified completion exactly once and isolates failed review", () => { const value = db(); const runtime = new HeidiLearningRuntime(value); const first = runtime.reviewCompletion({ completionKey: "run-1", sessionId: "s", verified: true, summary: "Use bounded verification evidence before applying this reusable recovery workflow.", evidence: ["verification:passed"] }); const second = runtime.reviewCompletion({ completionKey: "run-1", sessionId: "s", verified: true, summary: "different", evidence: [] }); expect(first.status).toBe("CANDIDATE_CREATED"); expect(second).toEqual(first); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 1 }); value.close() })
  it("records insufficient evidence and policy-blocked outcomes without durable candidates", () => { const value = db(); const runtime = new HeidiLearningRuntime(value); expect(runtime.reviewCompletion({ completionKey: "noisy", verified: false }).status).toBe("INSUFFICIENT_EVIDENCE"); expect(runtime.reviewCompletion({ completionKey: "blocked", verified: true, summary: "This is a verified reusable lesson with sufficient evidence.", policy: "off" }).status).toBe("POLICY_BLOCKED"); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 0 }); value.close() })
  it("persists tool-created candidates with non-sensitive provenance", async () => { const directory = mkdtempSync(join(tmpdir(), "heidi-learning-tool-")); mkdirSync(join(directory, ".flowdeck")); const execute = (heidiLearningTool as unknown as { execute: (args: Record<string, unknown>, context: { directory: string }) => Promise<string> }).execute; const result = JSON.parse(await execute({ action: "propose", type: "AGENT_MEMORY", content: "A controlled tool-created learning candidate with evidence.", confidence: 0.9, evidence: ["controlled:test"] }, { directory })); const value = new Database(join(directory, ".flowdeck", "flowdeck.db"), { readonly: true }); expect(result.type).toBe("AGENT_MEMORY"); expect(JSON.parse(result.provenance)).toEqual({ source: "heidi-learning-tool", repository: directory }); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 1 }); value.close() })
  it("suppresses duplicate candidates when source session is absent", () => { const value = db(); const runtime = new HeidiLearningRuntime(value); const input = { type: "AGENT_MEMORY" as const, content: "A duplicate candidate must be suppressed by content and type.", provenance: { source: "test" }, confidence: 0.8, evidence: ["test:duplicate"] }; const first = runtime.propose(input) as { id: string; status?: string }; const second = runtime.propose(input) as { candidateId?: string; status?: string }; expect(first.id).toBeTruthy(); expect(second).toMatchObject({ status: "DUPLICATE", candidateId: first.id }); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 1 }); value.close() })
  it("exposes controlled persistence failure without partial state and recovers", () => { const value = db(); value.exec("CREATE TRIGGER controlled_learning_failure BEFORE INSERT ON heidi_learning_candidates BEGIN SELECT RAISE(ABORT, 'controlled persistence failure'); END"); const runtime = new HeidiLearningRuntime(value); expect(runtime.reviewCompletion({ completionKey: "controlled-failure", verified: true, summary: "A verified candidate should persist after the controlled failure is removed.", evidence: ["controlled:failure"] }).status).toBe("PERSISTENCE_FAILED"); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 0 }); expect(value.query("SELECT status,error FROM heidi_completion_reviews WHERE completion_key=?").get("controlled-failure")).toMatchObject({ status: "failed", error: expect.stringContaining("controlled persistence failure") }); value.exec("DROP TRIGGER controlled_learning_failure"); const recovered = runtime.reviewCompletion({ completionKey: "recovered", verified: true, summary: "A verified candidate should persist after the controlled failure is removed.", evidence: ["controlled:recovery"] }); expect(recovered.status).toBe("CANDIDATE_CREATED"); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 1 }); value.close() })
  it("preserves candidate and review idempotency after database reopen", () => { const path = join(mkdtempSync(join(tmpdir(), "heidi-learning-reopen-")), "flowdeck.db"); let value = new Database(path); runMigrations(value); const first = new HeidiLearningRuntime(value).reviewCompletion({ completionKey: "restart", sessionId: "restart-session", verified: true, summary: "A restart-safe verified learning candidate persists with provenance.", evidence: ["restart:verified"] }); value.close(); value = new Database(path); runMigrations(value); const second = new HeidiLearningRuntime(value).reviewCompletion({ completionKey: "restart", sessionId: "restart-session", verified: true, summary: "different replay must not create another candidate.", evidence: [] }); expect(first.status).toBe("CANDIDATE_CREATED"); expect(second).toEqual(first); expect(value.query("SELECT COUNT(*) AS c FROM heidi_learning_candidates").get()).toEqual({ c: 1 }); expect(value.query("SELECT provenance FROM heidi_learning_candidates").get()).toMatchObject({ provenance: expect.stringContaining("restart") }); value.close() })
  it("dispatches registered tools through the pipeline executor", async () => { const calls: string[] = []; configureHeidiPipelineTools({ test: { execute: async (args) => { calls.push(String(args.value)); return { ok: true } } } }); const allowed = new Set(["test"]); const result = await executeToolPipeline([{ tool: "test", args: { value: "one" } }, { tool: "test", args: { value: "two" } }], allowed, getRegisteredPipelineExecutor(allowed, {}), { maxCalls: 2, timeoutMs: 1000, maxOutputBytes: 1000 }); expect(result.truncated).toBe(false); expect(calls).toEqual(["one", "two"]); await expect(executeToolPipeline([{ tool: "tool-pipeline", args: {} }], new Set(["tool-pipeline"]), async () => null, { maxCalls: 2, timeoutMs: 1000, maxOutputBytes: 1000 })).rejects.toThrow(); })
  it("supports scheduler lifecycle and restart-safe history", () => { const value = db(); const scheduler = new HeidiScheduler(value); const job = scheduler.create({ name: "nightly", prompt: "audit", scheduleType: "once", schedule: "2030-01-01T00:00:00.000Z", workspace: "/repo" }) as { id: string }; const run = scheduler.runNow(job.id) as { id: string }; scheduler.finish(run.id, "completed"); expect(scheduler.history(job.id)[0]).toMatchObject({ state: "completed" }); expect(scheduler.inspect(job.id)).toMatchObject({ enabled: 0 }); value.close() })
  it("executes a claimed scheduled job through the injected runtime and records failure safely", async () => { const value = db(); const scheduler = new HeidiScheduler(value); const job = scheduler.create({ name: "worker", prompt: "audit", scheduleType: "once", schedule: new Date(Date.now() - 1000).toISOString(), workspace: process.cwd() }) as { id: string }; let executed = false; const worker = new HeidiSchedulerWorker(scheduler, async received => { executed = received.id === job.id }); const result = await worker.runOnce(); expect(result.status).toBe("completed"); expect(executed).toBe(true); expect(scheduler.history(job.id)[0]).toMatchObject({ state: "completed" }); value.close() })
  it("projects delegated activity and refuses foreign control", () => { const value = db(); const runtime = new HeidiDelegationRuntime(value); runtime.queued({ childId: "child", parentSessionId: "parent", specialist: "tester", goal: "verify" }); expect(runtime.inspect("child", "other")).toBeNull(); expect(runtime.control("child", "cancel", undefined, "other").status).toBe("not_found_or_not_owned"); expect(runtime.control("child", "cancel", undefined, "parent").status).toBe("queued"); runtime.transition("child", "cancelled"); expect(runtime.inspect("child", "parent")).toMatchObject({ state: "cancelled" }); value.close() })
})
