import { describe, expect, it } from "bun:test"
import { execFileSync } from "node:child_process"
import { join } from "node:path"
import { validateV2Milestones } from "../scripts/verify-v2-milestones.mjs"
const script = join(process.cwd(), "scripts", "verify-v2-milestones.mjs")
const proof = { production: true, persistence: true, recovery: true, tests: true, sourceFiles: ["README.md"], testFiles: ["README.md"] }
const m9Proof: Record<string, unknown> = { ...proof, canonicalVerification: true, canonicalEvidence: true, canonicalCompletion: true, canonicalPlan: true, schedulerExecution: true, cancellation: true, tokenGovernance: true, tokenE2E: true, assignmentDispatch: true, ownershipWorktrees: true, worktreeE2E: true, restartMatrix: true, idempotency: true, historicalVersions: true, security: true }
describe("v2 milestone completion validator", () => { it("reports all nine milestones in the denominator", () => { const out = execFileSync(process.execPath, [script], { encoding: "utf8" }); expect(JSON.parse(out).completion).toBeCloseTo(88.8888888889) }); it("does not permit a false CLOSED claim without production evidence", () => { const report = { milestones: Array.from({ length: 9 }, (_, i) => ({ id: `M${i + 1}`, name: `M${i + 1}`, status: "CLOSED" })) }; expect(() => validateV2Milestones(report)).toThrow("without production") }); it("does not permit an excluded OPEN milestone", () => { const report = { milestones: Array.from({ length: 9 }, (_, i) => ({ id: `M${i + 1}`, name: `M${i + 1}`, status: i === 8 ? "OPEN" : "CLOSED", evidence: proof })) }; expect(() => validateV2Milestones(report)).not.toThrow(); expect(validateV2Milestones(report).completion).toBeCloseTo(88.8888888889) }) })
describe("v2 milestone completion validator", () => { it("rejects hand-edited completion rollups", () => { const report = { completion: 100, counts: { closed: 9, partial: 0, open: 0, superseded: 0 }, milestones: Array.from({ length: 9 }, (_, i) => ({ id: `M${i + 1}`, name: `M${i + 1}`, status: i < 2 ? "CLOSED" : "PARTIAL", ...(i < 2 ? { evidence: proof } : {}) })) }; expect(() => validateV2Milestones(report)).toThrow("completion rollup") }) })
describe("M9 executable evidence", () => { it("rejects closure when canonical authority proof is missing", () => { const evidence = { ...m9Proof }; delete evidence.canonicalCompletion; const report = { milestones: Array.from({ length: 9 }, (_, i) => ({ id: `M${i + 1}`, name: `M${i + 1}`, status: "CLOSED", evidence: i === 8 ? evidence : m9Proof })) }; expect(() => validateV2Milestones(report)).toThrow("canonicalCompletion") }) })
describe("M9 remaining executable evidence", () => { for (const key of ["tokenE2E", "assignmentDispatch", "worktreeE2E", "restartMatrix"]) it(`rejects closure when ${key} proof is missing`, () => { const evidence = { ...m9Proof }; delete evidence[key]; const report = { milestones: Array.from({ length: 9 }, (_, i) => ({ id: `M${i + 1}`, name: `M${i + 1}`, status: "CLOSED", evidence: i === 8 ? evidence : m9Proof })) }; expect(() => validateV2Milestones(report)).toThrow(key) }) })
