import { describe, expect, it, beforeEach, afterEach } from "bun:test"
import { Database } from "bun:sqlite"
import { runMigrations } from "../../src/orchestration/persistence/migrations/migration-runner"
import { createTransactionManager } from "../../src/orchestration/persistence/transaction-manager"
import { SqliteExecutionRepository, ExecutionScheduler, type ExecutionPlan } from "../../src/orchestration/execution"

describe("durable execution runtime persistence", () => {
  let db: Database; let repo: SqliteExecutionRepository
  beforeEach(() => { db = new Database(":memory:"); runMigrations(db); db.query("INSERT INTO contract_families VALUES ('f','f',NULL,'test',datetime('now'))").run(); db.query("INSERT INTO task_contracts(contract_id,family_id,version,title,description,repo_url,repo_sha,created_by,created_at) VALUES ('c','f',1,'c','c','https://example.test','0123456789abcdef0123456789abcdef01234567','test',datetime('now'))").run(); db.query("INSERT INTO task_runs(run_id,contract_id,strategy,state,baseline_sha,repo_branch,created_at,created_ts) VALUES ('run','c','planned','planning','0123456789abcdef0123456789abcdef01234567','main',datetime('now'),strftime('%s','now'))").run(); repo = new SqliteExecutionRepository(db, createTransactionManager(db)) })
  afterEach(() => db.close())
  const plan = (): ExecutionPlan => ({ planId: "plan", runId: "run", routingDecisionId: "decision", sourceSha: "0123456789abcdef0123456789abcdef01234567", policyVersion: "2.0.0", createdAt: "2026-08-09T00:00:00.000Z", workstreams: [{ workstreamId: "a", runId: "run", planId: "plan", resolvedAgent: "backend-coder", requiredCapability: "backend", objective: "implement", requirements: ["r"], acceptanceCriteria: ["a"], ownedPaths: ["src/api/a.ts"], ownedSymbols: [], dependsOn: [], strategy: "direct", budgetProfile: "normal", contextScope: "owned", status: "planned", blockedBy: [], createdAt: "2026-08-09T00:00:00.000Z" }] })
  it("round-trips plans and reconstructs ready workstreams", () => { const saved = repo.savePlan(plan()); expect(repo.getPlan("plan")).toEqual(saved); expect(repo.listReady("plan").map(w => w.workstreamId)).toEqual(["a"]); expect(() => repo.savePlan(plan())).toThrow("EXECUTION_PLAN_IMMUTABLE") })
  it("enforces legal transitions and durable lease exclusivity", () => { repo.savePlan(plan()); repo.transitionWorkstream("plan", "a", "ready"); repo.transitionWorkstream("plan", "a", "running"); const lease = { leaseId: "lease", runId: "run", planId: "plan", workstreamId: "a", agentId: "backend-coder", worktreeId: "wt", workspace: "/tmp/wt", branch: "fd/plan/a", acquiredAt: "2026-08-09T00:00:00.000Z", renewedAt: "2026-08-09T00:00:00.000Z", expiresAt: "2999-01-01T00:00:00.000Z" }; expect(repo.acquireLease(lease).state).toBe("allocated"); expect(() => repo.acquireLease({ ...lease, leaseId: "lease-2", agentId: "other" })).toThrow("WORKTREE_LEASE_CONFLICT"); expect(repo.releaseLease("lease").state).toBe("released") })
  it("reclaims expired leases and rejects duplicate integration", () => { repo.savePlan(plan()); const lease = { leaseId: "lease", runId: "run", planId: "plan", workstreamId: "a", agentId: "a", worktreeId: "wt", workspace: "/tmp/wt", branch: "fd/plan/a", acquiredAt: "2020-01-01T00:00:00.000Z", renewedAt: "2020-01-01T00:00:00.000Z", expiresAt: "2020-01-01T00:00:00.000Z" }; repo.acquireLease(lease); expect(repo.reclaimExpired("2021-01-01T00:00:00.000Z")).toBe(1); const attempt = { attemptId: "i", planId: "plan", workstreamId: "a", sourceSha: lease.branch.padEnd(40, "0").slice(0, 40), branch: lease.branch, status: "integrated" as const, verification: {}, evidence: {}, createdAt: "2026-08-09T00:00:00.000Z" }; repo.recordIntegration(attempt); expect(repo.hasIntegrated("a")).toBe(true); expect(() => repo.recordIntegration(attempt)).toThrow() })
  it("runs independent work in parallel and blocks dependents after failure", async () => { const p = plan(); p.planId = "plan-2"; p.workstreams = [{ ...p.workstreams[0], workstreamId: "a", planId: "plan-2", ownedPaths: ["src/a.ts"] }, { ...p.workstreams[0], workstreamId: "b", planId: "plan-2", ownedPaths: ["src/b.ts"] }, { ...p.workstreams[0], workstreamId: "c", planId: "plan-2", ownedPaths: ["src/c.ts"], dependsOn: ["a"] }]; repo.savePlan(p); const scheduler = new ExecutionScheduler(repo); const result = await scheduler.runReady("plan-2", { execute: async w => w.workstreamId === "a" ? "failed" : "succeeded" }); expect(result.started).toEqual(["a", "b"]); expect(result.failed).toEqual(["a"]); expect(result.succeeded).toEqual(["b"]); expect(repo.getPlan("plan-2")!.workstreams.find(w => w.workstreamId === "c")!.status).toBe("blocked") })
})
