import { describe, expect, it, beforeEach, afterEach } from "bun:test"
import { Database } from "bun:sqlite"
import { runMigrations } from "../../src/orchestration/persistence/migrations/migration-runner"
import { createTransactionManager } from "../../src/orchestration/persistence/transaction-manager"
import { SqlitePerformanceRepository } from "../../src/orchestration/performance"
import { OrchestrationMetrics } from "../../src/orchestration/metrics"
import { unlinkSync } from "node:fs"
const observation = (id: string, agent = "agent", capability = "backend") => ({ observationId: id, runId: `run-${id}`, workstreamId: `ws-${id}`, agentId: agent, capability, taskClass: "feature", strategy: "direct", complexityBand: "medium" as const, riskBand: "low" as const, success: true, verificationPassed: true, integrationPassed: true, tokenReserved: 100, tokenUsed: 50, durationMs: 100, retryCount: 0, reviewFindings: 0, regressionCount: 0, terminationReason: "completed", usefulnessSignals: ["artifact"], policyVersion: "1.0.0", createdAt: "2026-08-09T00:00:00.000Z" })
describe("durable performance profiles", () => { let db: Database; let repo: SqlitePerformanceRepository; beforeEach(() => { db = new Database(":memory:"); runMigrations(db); repo = new SqlitePerformanceRepository(db, createTransactionManager(db)) }); afterEach(() => db.close()); it("persists immutable observations and applies minimum samples", () => { repo.saveObservation(observation("1")); expect(repo.getObservation("1")?.agentId).toBe("agent"); expect(repo.profile("agent", "backend").status).toBe("insufficient_data"); repo.saveObservation(observation("2")); repo.saveObservation(observation("3")); expect(repo.profile("agent", "backend").status).toBe("eligible"); expect(() => repo.saveObservation(observation("1"))).toThrow("PERFORMANCE_OBSERVATION_IMMUTABLE") }); it("keeps capability profiles isolated", () => { repo.saveObservation(observation("1", "agent", "security")); repo.saveObservation(observation("2", "agent", "security")); repo.saveObservation(observation("3", "agent", "security")); expect(repo.profile("agent", "backend").sampleCount).toBe(0); expect(repo.profile("agent", "security").sampleCount).toBe(3) }); it("excludes stale observations without deleting immutable history", () => { repo.saveObservation({ ...observation("old-1"), createdAt: "2020-01-01T00:00:00.000Z", success: false }); repo.saveObservation({ ...observation("old-2"), createdAt: "2020-01-01T00:00:00.000Z", success: false }); repo.saveObservation({ ...observation("old-3"), createdAt: "2020-01-01T00:00:00.000Z", success: false }); repo.saveObservation(observation("new-1")); repo.saveObservation(observation("new-2")); repo.saveObservation(observation("new-3")); expect(repo.profile("agent", "backend").sampleCount).toBe(3); expect(repo.getObservation("old-2")?.success).toBe(false) }); it("reconstructs immutable observations and metrics after database restart", () => { const path = `/tmp/flowdeck-performance-${process.pid}-${Date.now()}.db`; db.close(); db = new Database(path); runMigrations(db); const metrics = new OrchestrationMetrics(); repo = new SqlitePerformanceRepository(db, createTransactionManager(db), metrics); repo.saveObservation(observation("restart-1")); expect(metrics.snapshot().find(metric => metric.name === "agent_performance_observations_total")?.value).toBe(1); db.close(); db = new Database(path); runMigrations(db); repo = new SqlitePerformanceRepository(db, createTransactionManager(db)); expect(repo.getObservation("restart-1")).toEqual(observation("restart-1")); expect(repo.profile("agent", "backend").sampleCount).toBe(1); db.close(); unlinkSync(path) }) })
